source 'https://gitee.com/zhenlove/zhenSpecs.git'
source 'https://cdn.cocoapods.org/'
use_frameworks!
inhibit_all_warnings!
platform :ios, '9.0'

target 'KMAgoraRtc_Example' do
  pod 'KMRouter','0.1.4'
  pod 'KMAgoraRtc',:path => '../'
end
